#!/usr/bin/env python3
"""
Cave Entrance Finder Tool for mod-playerbots-betterquesting

This tool finds entrance points for detected caves by analyzing spawn patterns
and looking for surface spawns near underground clusters.

Reads cave candidates from the database (generated by cave_detector.py) and
outputs approach waypoint data.

Usage:
    python cave_entrance_finder.py --host localhost --user root --password pass --database acore_world

Output:
    Generates SQL file with approach waypoints for cave entrances.
"""

import argparse
import math
import sys
from collections import defaultdict

try:
    import mysql.connector
except ImportError:
    print("Error: mysql-connector-python is required. Install with: pip install mysql-connector-python")
    sys.exit(1)


# Constants for entrance finding
ENTRANCE_SEARCH_RADIUS = 100.0  # Search radius around cave center
ENTRANCE_SEARCH_RINGS = [30.0, 50.0, 75.0, 100.0]  # Radii to sample
SAMPLES_PER_RING = 16  # Number of sample points per ring
MAX_ENTRANCE_SURFACE_DIFF = 15.0  # Max difference from surface to be considered an entrance


def connect_to_database(host, user, password, database, port=3306):
    """Connect to the MySQL database."""
    try:
        conn = mysql.connector.connect(
            host=host,
            user=user,
            password=password,
            database=database,
            port=port
        )
        return conn
    except mysql.connector.Error as err:
        print(f"Error connecting to database: {err}")
        sys.exit(1)


def load_cave_candidates(conn):
    """Load cave candidates from the database."""
    cursor = conn.cursor(dictionary=True)

    query = """
    SELECT caveId, mapId, zoneId, centerX, centerY, caveZ, surfaceZ, depth, spawnCount, sampleNames
    FROM playerbots_questing_cave_candidates
    WHERE verified != 2
    ORDER BY mapId, spawnCount DESC
    """

    try:
        cursor.execute(query)
        results = cursor.fetchall()
    except mysql.connector.Error:
        print("Warning: playerbots_questing_cave_candidates table not found.")
        print("Run cave_detector.py first to generate cave candidates.")
        results = []

    cursor.close()
    return results


def find_surface_spawns_near_cave(conn, cave, search_radius=ENTRANCE_SEARCH_RADIUS):
    """
    Find surface-level spawns near a cave location.

    These spawns indicate where paths exist that players can walk.
    """
    cursor = conn.cursor(dictionary=True)

    map_id = cave['mapId']
    x = cave['centerX']
    y = cave['centerY']
    surface_z = cave['surfaceZ']

    # Find creatures near surface level around the cave
    query = """
    SELECT
        c.guid,
        c.id1 as entry,
        c.position_x as x,
        c.position_y as y,
        c.position_z as z,
        ct.name
    FROM creature c
    LEFT JOIN creature_template ct ON c.id1 = ct.entry
    WHERE c.map = %s
    AND ABS(c.position_x - %s) < %s
    AND ABS(c.position_y - %s) < %s
    AND ABS(c.position_z - %s) < %s
    ORDER BY
        SQRT(POW(c.position_x - %s, 2) + POW(c.position_y - %s, 2))
    """

    cursor.execute(query, (
        map_id, x, search_radius, y, search_radius,
        surface_z, MAX_ENTRANCE_SURFACE_DIFF,
        x, y
    ))

    results = cursor.fetchall()
    cursor.close()

    return results


def find_transition_spawns(conn, cave, search_radius=ENTRANCE_SEARCH_RADIUS):
    """
    Find spawns that might be in the transition zone between surface and underground.

    These are spawns that are between surface Z and cave Z, potentially indicating
    a sloped entrance or tunnel.
    """
    cursor = conn.cursor(dictionary=True)

    map_id = cave['mapId']
    x = cave['centerX']
    y = cave['centerY']
    cave_z = cave['caveZ']
    surface_z = cave['surfaceZ']

    # Find creatures in the transition zone
    mid_z = (cave_z + surface_z) / 2
    transition_range = (surface_z - cave_z) / 2

    query = """
    SELECT
        c.guid,
        c.id1 as entry,
        c.position_x as x,
        c.position_y as y,
        c.position_z as z,
        ct.name,
        SQRT(POW(c.position_x - %s, 2) + POW(c.position_y - %s, 2)) as distance_2d
    FROM creature c
    LEFT JOIN creature_template ct ON c.id1 = ct.entry
    WHERE c.map = %s
    AND ABS(c.position_x - %s) < %s
    AND ABS(c.position_y - %s) < %s
    AND c.position_z BETWEEN %s AND %s
    ORDER BY distance_2d
    LIMIT 50
    """

    cursor.execute(query, (
        x, y,
        map_id, x, search_radius, y, search_radius,
        cave_z - 10, surface_z + 10
    ))

    results = cursor.fetchall()
    cursor.close()

    return results


def estimate_entrance_location(cave, surface_spawns, transition_spawns):
    """
    Estimate the cave entrance location based on spawn patterns.

    Strategy:
    1. Look for transition spawns that form a path from surface to cave
    2. Use the outermost transition spawn as the entrance estimate
    3. Fall back to the closest surface spawn if no transition found
    """
    if not surface_spawns and not transition_spawns:
        return None

    cave_x = cave['centerX']
    cave_y = cave['centerY']
    surface_z = cave['surfaceZ']

    # Sort transition spawns by distance from cave center (farthest first for entrance)
    if transition_spawns:
        # Find the spawn in transition zone that's farthest from cave center
        # but still reasonably close - this is likely the entrance
        transition_spawns.sort(key=lambda s: -s.get('distance_2d', 0))

        for spawn in transition_spawns:
            dist = spawn.get('distance_2d', 0)
            # Good entrance candidate: between 20-80 yards from cave center
            if 20 < dist < 80:
                return {
                    'x': spawn['x'],
                    'y': spawn['y'],
                    'z': spawn['z'],
                    'source': 'transition_spawn',
                    'distance': dist
                }

    # Fall back to closest surface spawn
    if surface_spawns:
        # Sort by distance to cave center
        surface_spawns.sort(key=lambda s: math.sqrt(
            (s['x'] - cave_x) ** 2 + (s['y'] - cave_y) ** 2
        ))

        spawn = surface_spawns[0]
        dist = math.sqrt((spawn['x'] - cave_x) ** 2 + (spawn['y'] - cave_y) ** 2)

        return {
            'x': spawn['x'],
            'y': spawn['y'],
            'z': spawn['z'],
            'source': 'surface_spawn',
            'distance': dist
        }

    return None


def generate_approach_waypoints(cave, entrance):
    """
    Generate approach waypoints from the entrance to the cave center.

    Creates a simple 2-waypoint path:
    1. Entrance (approach point)
    2. Cave center (final destination)
    """
    if not entrance:
        return []

    waypoints = []

    # Waypoint 1: Entrance point
    waypoints.append({
        'order': 0,
        'x': entrance['x'],
        'y': entrance['y'],
        'z': entrance['z'],
        'radius': 5.0,
        'description': f"Cave entrance ({entrance['source']})"
    })

    # Waypoint 2: Approach to cave (midpoint if entrance is far)
    dist = entrance.get('distance', 0)
    if dist > 40:
        # Add intermediate waypoint
        mid_x = (entrance['x'] + cave['centerX']) / 2
        mid_y = (entrance['y'] + cave['centerY']) / 2
        mid_z = (entrance['z'] + cave['caveZ']) / 2

        waypoints.append({
            'order': 1,
            'x': mid_x,
            'y': mid_y,
            'z': mid_z,
            'radius': 8.0,
            'description': 'Cave interior approach'
        })

    return waypoints


def generate_sql_output(results, output_file):
    """Generate SQL file with approach waypoints."""
    with open(output_file, 'w') as f:
        f.write("-- Cave entrance approach waypoints generated by cave_entrance_finder.py\n")
        f.write("-- These waypoints help bots navigate to quest objectives inside caves\n\n")

        f.write("-- First, update cave candidates with found entrances\n")
        for cave, entrance, waypoints in results:
            if entrance:
                f.write(f"UPDATE `playerbots_questing_cave_candidates` SET ")
                f.write(f"entranceX = {entrance['x']:.2f}, ")
                f.write(f"entranceY = {entrance['y']:.2f}, ")
                f.write(f"entranceZ = {entrance['z']:.2f} ")
                f.write(f"WHERE caveId = {cave['caveId']};\n")

        f.write("\n-- Insert approach waypoints for zones containing caves\n")
        f.write("-- These are ZONE-level waypoints that help bots approach cave areas\n\n")

        # Group by zone for zone-level approach waypoints
        zone_waypoints = defaultdict(list)
        for cave, entrance, waypoints in results:
            if entrance and cave.get('zoneId', 0) > 0:
                zone_id = cave['zoneId']
                zone_waypoints[zone_id].append((cave, entrance, waypoints))

        # Generate zone-level approach waypoints
        waypoint_id = 1
        for zone_id, caves in sorted(zone_waypoints.items()):
            if not caves:
                continue

            f.write(f"-- Zone {zone_id} cave entrances\n")
            for cave, entrance, waypoints in caves:
                map_id = cave['mapId']
                sample_names = cave.get('sampleNames', 'Unknown')

                for wp in waypoints:
                    f.write(f"INSERT INTO `playerbots_questing_approach_waypoints` ")
                    f.write(f"(`targetType`, `targetId`, `mapId`, `waypointOrder`, `x`, `y`, `z`, `radius`, `description`) VALUES ")
                    f.write(f"(0, {zone_id}, {map_id}, {wp['order']}, {wp['x']:.2f}, {wp['y']:.2f}, {wp['z']:.2f}, ")
                    f.write(f"{wp['radius']:.1f}, 'Cave entrance for {sample_names[:50]}');\n")
                    waypoint_id += 1

            f.write("\n")

        f.write(f"\n-- Total approach waypoints generated: {waypoint_id - 1}\n")


def main():
    parser = argparse.ArgumentParser(description='Find cave entrances for approach waypoints')
    parser.add_argument('--host', default='localhost', help='MySQL host')
    parser.add_argument('--port', type=int, default=3306, help='MySQL port')
    parser.add_argument('--user', default='root', help='MySQL user')
    parser.add_argument('--password', default='', help='MySQL password')
    parser.add_argument('--database', default='acore_world', help='Database name')
    parser.add_argument('--output', default='cave_entrances.sql', help='Output SQL file')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')

    args = parser.parse_args()

    print("Connecting to database...")
    conn = connect_to_database(args.host, args.user, args.password, args.database, args.port)

    print("Loading cave candidates...")
    caves = load_cave_candidates(conn)

    if not caves:
        print("No cave candidates found. Run cave_detector.py first.")
        conn.close()
        return

    print(f"Found {len(caves)} cave candidates")

    results = []
    entrances_found = 0

    print("\nFinding entrance locations...")
    for cave in caves:
        if args.verbose:
            print(f"  Processing cave {cave['caveId']}: "
                  f"map={cave['mapId']} zone={cave.get('zoneId', 0)} "
                  f"pos=({cave['centerX']:.0f}, {cave['centerY']:.0f})")

        # Find surface and transition spawns
        surface_spawns = find_surface_spawns_near_cave(conn, cave)
        transition_spawns = find_transition_spawns(conn, cave)

        # Estimate entrance location
        entrance = estimate_entrance_location(cave, surface_spawns, transition_spawns)

        if entrance:
            entrances_found += 1
            if args.verbose:
                print(f"    Found entrance at ({entrance['x']:.0f}, {entrance['y']:.0f}, {entrance['z']:.0f}) "
                      f"via {entrance['source']}")

        # Generate waypoints
        waypoints = generate_approach_waypoints(cave, entrance)

        results.append((cave, entrance, waypoints))

    print(f"\nFound entrances for {entrances_found} of {len(caves)} caves "
          f"({100*entrances_found/len(caves):.1f}%)")

    print(f"\nGenerating SQL output: {args.output}")
    generate_sql_output(results, args.output)

    conn.close()
    print("\nDone!")


if __name__ == '__main__':
    main()
